language: python
python:
    - 2.7
install: 
    - pip install . --use-mirrors
    - pip install coveralls
before_script:
    - psql -c 'create database krankshaft;' -U postgres
script:
    - python setup.py test
after_success:
    - coveralls
